pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Build Client in Ubuntu
      - -title ~=@angular\/
    actions:
      merge:
        method: merge
